cinemaster/cinemaster/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('my_auth.urls')),
    url(r'^sessions/', include('session.urls')),
    url(r'^', include('movies.urls')),
]

cinemaster/movies/urls.py
from django.conf.urls import url

from . import views


app_name = 'movies'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^movie/(?P<movie_id>[0-9]+)$', views.detail, name='detail'),
    url('^edit_review/(?P<movie_id>[0-9]+)', views.edit_review, name='edit_review'),
    url('^post_review/(?P<movie_id>[0-9]+)', views.post_review, name='post_review'),
    url('^delete_review/(?P<movie_id>[0-9]+)', views.delete_review, name='delete_review'),
]

cinemaster/session/urls.py
from django.conf.urls import url

from . import views

app_name = 'session'
urlpatterns = [
    url('^$', views.index, name='index'),
    url('^book/(?P<session_id>[0-9]+)$', views.book, name='book'),
    url('^buy_tickets/(?P<session_id>[0-9]+)$', views.buy_tickets, name='buy_tickets'),
]

cinemaster/session/models.py
from django.db import models

# Create your models here.

cinemaster/session/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect

import sqlite3
import datetime

from .utilities import *

def index(request):
    with connect() as con:
        sessions = con.execute('SELECT * FROM sessions NATURAL JOIN movies').fetchall()

    return render(request, 'session/index.html', {'sessions': sessions})


def book(request, session_id):
    with connect() as con:
        free_seats = con.execute('SELECT * FROM tickets NATURAL JOIN seats '
                                 'WHERE session_id = ? AND sold = 0', (session_id,)).fetchall()
    return render(request, 'session/book.html',
                  {'free_seats':free_seats,
                   'session_id':session_id})


def buy_tickets(request, session_id):
    tickets = request.POST.getlist('seat_id')

    if not tickets or not verify_token_belongs_to_user(request.COOKIES['auth_token'],
                                                       request.COOKIES['user_id']):
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    with connect() as con:
        for ticket in tickets:
            con.execute('UPDATE tickets SET sold = 1, user_id = ? WHERE seat_id = ? AND session_id = ?',
                        (request.COOKIES['user_id'], ticket, session_id))
        con.commit()

    return HttpResponseRedirect(reverse('session:index'))

cinemaster/session/templates/session/book.html
{% extends 'base.html' %}

{% block title %}Бронирование{% endblock %}

{% block content %}
<form action="{% url 'session:buy_tickets' session_id %}" method="post">
    {% csrf_token %}
    {% for seat in free_seats %}
    <input type="checkbox" name="seat_id" value="{{ seat.seat_id }}" />
        Ряд {{ seat.row_no }}, место {{ seat.seat_no }}.
        Тип: {% if seat.special_features != 'NULL' %}{{ seat.special_features }}{% else %}обычное место{% endif %}.
        Цена: {{ seat.amount }}.
    <br />
    {% endfor %}
    {% if request.COOKIES.auth_token %}
    <input type="submit" value="Бронировать" />
    {% else %}
    Войдите на сайт, чтобы бронировать места.
    {% endif %}
</form>
{% endblock %}

cinemaster/session/templates/session/index.html
{% extends 'base.html' %}

{% block title %}Сеансы{% endblock %}

{% block content %}
{% for session in sessions %}
<p>
    Фильм: {{ session.title }} <br />
    Начало показа: {{ session.begin_time }} <br />
    <a href="{% url 'session:book' session.session_id %}">Перейти к бронированию мест</a>
</p>
{% endfor %}
{% endblock %}