cinemaster/cinemaster/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('my_auth.urls')),
    url(r'^sessions/', include('session.urls')),
    url(r'^', include('movies.urls')),
]

cinemaster/movies/urls.py
from django.conf.urls import url

from . import views


app_name = 'movies'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^movie/(?P<movie_id>[0-9]+)$', views.detail, name='detail'),
    url('^edit_review/(?P<movie_id>[0-9]+)', views.edit_review, name='edit_review'),
    url('^post_review/(?P<movie_id>[0-9]+)', views.post_review, name='post_review'),
    url('^delete_review/(?P<movie_id>[0-9]+)', views.delete_review, name='delete_review'),
]

cinemaster/movies/models.py
from django.db import models


class User(models.Model):
    password = models.CharField(max_length=64)
    display_name = models.CharField(max_length=30)


class Movie(models.Model):
    title = models.CharField(max_length=200)
    release_date = models.DateField()
    director = models.CharField(max_length=200)
    language = models.CharField(max_length=60)
    subtitles = models.CharField(max_length=60)
    age_restriction = models.IntegerField()
    duration = models.IntegerField()
    box_office = models.FloatField()
    rating_sum = models.IntegerField(default=0)
    reviews_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Session(models.Model):
    movie_id = models.ForeignKey(Movie, on_delete=models.CASCADE)
    begin_time = models.DateTimeField()
    end_time = models.DateTimeField()
    hall_no = models.IntegerField()


class Review(models.Model):
    movie_id = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    review = models.TextField()
    pub_date = models.DateTimeField()

cinemaster/movies/views.py
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render

from .utilities import *

def index(request):
    with connect() as con:
        movies_list = con.execute('SELECT * FROM movies').fetchall()
        return render(request, 'movies/index.html', {'movies_list':movies_list})


def detail(request, movie_id):

    user_id = request.COOKIES.get('user_id')
    have_review = False

    with connect() as con:
        if user_id:
            have_review = True if con.execute('SELECT * FROM reviews WHERE movie_id = ? AND user_id = ?',
                                             (movie_id, user_id)).fetchone() else False
        movie = con.execute('SELECT * FROM movies WHERE movie_id = ?', (movie_id,)).fetchone()
        reviews = con.execute('SELECT * FROM reviews NATURAL JOIN users WHERE movie_id = ?', (movie_id,)).fetchall()
        reviews_count = len(reviews)
        rating_sum = con.execute('SELECT sum(rating) as rating_sum FROM reviews').fetchone()['rating_sum']

    if not movie:
        raise Http404("Фильм не существует")

    if reviews_count:
        rating = rating_sum / reviews_count
    else:
        rating = None

    return render(request, 'movies/detail.html',
                  {'movie':movie,
                   'rating':rating,
                   'reviews': reviews,
                   'have_review': have_review})


def edit_review(request, movie_id):
    user_id = request.COOKIES.get('user_id')
    if not user_id:
        return HttpResponseRedirect(reverse('movies:index'))

    with connect() as con:
        review = con.execute('SELECT * FROM reviews WHERE movie_id = ? AND user_id = ?',
                             (movie_id, user_id)).fetchone()
        movie = con.execute('SELECT * FROM movies WHERE movie_id = ?', (movie_id,)).fetchone()

    return render(request, 'movies/edit_review.html', {'movie':movie, 'review':review})


def post_review(request, movie_id):
    user_id = request.COOKIES.get('user_id')
    auth_token = request.COOKIES.get('auth_token')

    if not user_id or not auth_token or not verify_token_belongs_to_user(auth_token, user_id):
        return HttpResponseRedirect(reverse('movies:detail', kwargs={'movie_id':movie_id}))

    with connect() as con:
        review = con.execute('SELECT * FROM reviews WHERE movie_id = ? AND user_id = ?',
                             (movie_id, user_id)).fetchone()
        if review:
            con.execute('UPDATE reviews SET rating = ?, review = ? WHERE user_id = ? AND movie_id = ?;',
                        (request.POST['rating'], request.POST['review'], user_id, movie_id))
        else:
            con.execute('INSERT INTO reviews VALUES (?, ?, ?, ?);',
                        (movie_id, user_id, request.POST['rating'], request.POST['review']))

        con.commit()

    return HttpResponseRedirect(reverse('movies:detail', kwargs={'movie_id':movie_id}))


def delete_review(request, movie_id):
    user_id = request.COOKIES.get('user_id')
    auth_token = request.COOKIES.get('auth_token')

    if not user_id or not auth_token or not verify_token_belongs_to_user(auth_token, user_id):
        return HttpResponseRedirect(reverse('movies:detail', kwargs={'movie_id': movie_id}))

    with connect() as con:
        con.execute('DELETE FROM reviews WHERE user_id = ? AND movie_id = ?;', (user_id, movie_id))
        con.commit()

    return HttpResponseRedirect(reverse('movies:detail', kwargs={'movie_id': movie_id}))

cinemaster/movies/templates/movies/detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ movie.title }}{% endblock %}

{% block content %}
<div class="movie-description">
    <div class="movie-info">
        <h2>{{ movie.title }}</h2>
        <ul>
            <li>
                Год выхода: {{ movie.release_year }}
            </li>
            <li>
                Режиссер: {{ movie.director }}
            </li>
            <li>
                Язык: {{ movie.language }}
            </li>
            <li>
                Субтитры: {% if movie.subtitles %}{{ movie.subtitles }}{% else %}нет{% endif %}
            </li>
            <li>
                Возрастные ограничения:
                {% if movie.age_restriction %}{{ movie.age_restriction }}{% else %}нет{% endif %}
            </li>
            <li>
                Продолжительность: {{ movie.duration }} минут
            </li>
            <li>
                Кассовые сборы: {% if movie.box_office %}{{ movie.box_office }}{% else %}не известны{% endif %}
            </li>
            <li>
                Рейтинг: {% if rating %}{{ rating }}{% else %}не известен{% endif %}
            </li>
        </ul>
    </div>
{% if movie.poster %}
    <div class="movie-poster">
        <img src="{{  movie.poster }}" width="240px" />
    </div>
{% endif %}
{% if movie.description %}
    <div class="movie-summary">
        <p>{{ movie.description }}</p>
    </div>
{% endif %}
</div>

<div class="review-box">
    <div style="text-align: center;">
    {% if have_review %}
    <a href="{% url 'movies:edit_review' movie.movie_id %}">Редактировать обзор</a>
    <br/>
    <a href="{% url 'movies:delete_review' movie.movie_id %}">Удалить обзор</a>
    {% elif request.COOKIES.user_id %}
    <a href="{% url 'movies:edit_review' movie.movie_id %}">Написать обзор</a>
    {% endif %}
    </div>

    {% for review in reviews %}
    <div class="review">
        <p>Обзор пользователя <strong>{{ review.login }}</strong>:</p>
        <p>Оценка: <strong>{{ review.rating }}</strong></p>
        <p>
            {{ review.review }}
        </p>
    </div>
    {% endfor %}
</div>
{% endblock %}

cinemaster/movies/templates/movies/edit_review.html
{% extends 'base.html' %}

{% block title %}Редактирование обзора{% endblock %}

{% block content %}
<h2>Ваш обзор на фильм {{ movie.title }}</h2>
<form action="{% url 'movies:post_review' movie.movie_id %}" method="post">
    {% csrf_token %}
    Ваша оценка: <br/>
    {% for rating in "xxxxxxxxxx" %}
    <input type="radio" name="rating" value="{{ forloop.counter }}"
     {% if review and review.rating == forloop.counter %} checked {% endif %}/>
    {{ forloop.counter }}
    {% endfor %}
    <br />
    <textarea name="review" rows="12" cols="80">{% if review %}{{ review.review }}{% endif %}</textarea>
    <br />
    <input type="submit" value="Отправить" />
</form>
{% endblock %}

cinemaster/movies/templates/movies/index.html
{% extends "base.html" %}

{% block title %}Главная{% endblock %}

{% block content %}
    <p>
    Сейчас в показе:
    <ul>
    {% for movie in movies_list %}
        <li><a href="{% url 'movies:detail' movie.movie_id %}">{{ movie.title }}</a></li>
    {% endfor %}
    </ul>
    </p>
{% endblock %}